default: &default
  adapter: postgresql
  encoding: unicode
  host: host-do-banco
  database: nome-do-banco
  username: nome-do-usuario
  password: senha-do-usuario
  port: 5432
  sslmode: require
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: todo_list_test

production:
  <<: *default